---
- name: Create the host definition
  vars:
    __nagiosconfig_host_vars: "{{ lookup('ansible.builtin.file', __nagiosconfig_host_file) | from_yaml }}"
    __nagiosconfig_host: "{{ __nagiosconfig_host_vars._host | default({}) }}"
  ansible.builtin.template:
    src: host_definition.cfg.j2
    dest: "{{ __nagiosconfig_stage_dir }}/hosts/{{ __nagiosconfig_host.host_name }}.cfg"
    mode: "0664"
    force: "{{ nagiosconfig_mode == 'always' }}"
  check_mode: false
  when: __nagiosconfig_host | length > 0

- name: Create the service definitions
  vars:
    __nagiosconfig_host_vars: "{{ lookup('ansible.builtin.file', __nagiosconfig_host_file) | from_yaml }}"
    __nagiosconfig_host: "{{ __nagiosconfig_host_vars._host | default({}) }}"
    __nagiosconfig_services: "{{ __nagiosconfig_host_vars._services | default({}) }}"
  ansible.builtin.template:
    src: service_definition.cfg.j2
    dest: "{{ __nagiosconfig_stage_dir }}/services/{{ __nagiosconfig_host.host_name }}.cfg"
    mode: "0664"
    force: "{{ nagiosconfig_mode == 'always' }}"
  check_mode: false
  when: __nagiosconfig_services | length > 0
