---
- name: Set target dependent variables
  ansible.builtin.import_tasks: vars.yml
  tags:
    - nagiosconfig
    - nagiosconfig-config

- name: Load the monitoring objects from the inventory
  ansible.builtin.import_tasks: objects_load.yml
  tags:
    - nagiosconfig
    - nagiosconfig-config

- name: Install the extra plugins
  ansible.builtin.import_tasks: plugins.yml
  tags:
    - nagiosconfig
    - nagiosconfig-config

- name: Configure nagios monitoring objects
  ansible.builtin.import_tasks: objects.yml
  tags:
    - nagiosconfig
    - nagiosconfig-config
  when: nagiosconfig_mode != 'never'
